// <auto-generated />
namespace FrontendSpike.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201303261646060_CreateUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
